version: '3'

services:

    db:
        image: postgres:${POSTGRES_VERSION:-14}-alpine
        environment:
            POSTGRES_DB: ${DATABASE_NAME:-app}
            POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-default}
            POSTGRES_USER: ${DATABASE_USER:-default}
        volumes:
            - db-data:/var/lib/postgresql/data:rw

volumes:
    db-data:
